name: snakemake
channels:
  - conda-forge
  - bioconda
dependencies:
  - numpy==1.18.5
  - matplotlib==3.2.1
  - snakemake==5.27.4
  - graphviz==2.42.3 
  - pycodestyle
  - sphinx
  - sphinx_rtd_theme
